apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: jobs
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-dns
            image: robbash/update-dns
            env:
            - name: DEBUG
              value: "true"
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: authToken
            - name: ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: zoneId
            - name: RECORD_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: recordId
            - name: RECORD_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: recordName
          restartPolicy: OnFailure
